### ISSUE TITLE
User can view their profile

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/code-journal#2]

**Comment by keivanmojmali** [comment]
## 💰 Motivation

Coders will want to capture tidbits they pick up during their research.

## 📐 Plan

Create a responsive form that allows users to store an image URL with some notes about a specific topic.

## 🖼️ Wireframe

![user can create an entry](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/user-can-create-an-entry.png)

## ✅ Task List

- [ ] Add a `div[data-view="entries"]` to the HTML.
- [ ] Add a link to the navbar to show the `'entries'` view.
- [ ] Verify that a user can only see the `'entries'` view if they have a profile already.
- [ ] Add a `div[data-view="create-entry"]` to the HTML.
- [ ] Add a form for creating a journal entry to the `div[data-view="create-entry"]`.
- [ ] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [ ] Make all inputs of the journal entry form `required`.
- [ ] Add a link to the `'entries'` view that navigates the user to the `'create-entry'` view.
- [ ] Listen for `'input'` events on the `photoUrl` input to update the photo preview when the input value changes.
- [ ] Listen for `'submit'` events on the journal entry form and:
  - [ ] Put the form's input values into a new object.
  - [ ] Prepend the new object to the entries in the data model.
  - [ ] Reset the image preview's `src' attribute.
  - [ ] Reset the form inputs.
  - [ ] Show the `'entries'` view again.
- [ ] Verify that new entries are saved to local storage along with the rest of the data model on reload.
- [ ] Verify that a brand new user cannot go to the `'entries'` view if they haven't created their profile.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again.
- [ ] Fix all bugs.

**Comment by keivanmojmali** [comment]
## 💰 Motivation

Users will want to check what information they have told us about themselves.

## 📐 Plan

Create a separate view that dynamically renders the user's profile details.

## 🖼️ Wireframe

![user can view their profile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/user-can-view-their-profile.png)

## ✅ Task List

- [x] Hide the `div[data-view="edit-profile"]` view in the HTML.
- [x] Add a new `div[data-view="profile"]` to the HTML to display the user's profile information.
- [x] Build an example profile in the `data-view="profile"` with HTML and CSS.
- [x] Ensure that the profile view looks good on both mobile and desktop.
- [x] Define a JavaScript function that takes the profile data model and returns a DOM tree that matches the HTML.
- [x] Define a JavaScript view swapping function that takes the name of which `data-view` to show and hides all others.
- [x] Make the view swapping function also write the name of the view it showed to the application's data model.
- [x] Test the view swapping function by hand in the browser console, passing it `'edit-profile'` or `'profile'` as an argument.
  - [x] Update the view swapping function to empty out the content of the `div[data-view="profile"]` when showing the `'profile'`.
  - [x] Update the view swapping function to append the return value of the profile rendering function to the `div[data-view="profile"]` when showing the `'profile'`.
- [x] Update the `'submit'` event listener on the form to show the `'profile'` view after profile data model has been updated.
- [x] Listen to the `document` for `'DOMContentLoaded'`.
  - [x] If the user has not saved a `username`, show the profile form, otherwise show the `view` that was written to the data model.
  - [x] Use a private browsing tab to test that a new user sees the form when the page loads.
  - [x] Verify that a returning user sees their profile when the page loads.
- [x] Delete the reference profile from the HTML code so that the `div[data-view="profile"]` is initially empty.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
- [x] Fix all bugs.
